routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', 'App\Http\Controllers\MainController@show')->name('index');

Route::get('/find', function () {
    return view('guest.find');
})->name('find');

Route::post('/find/submit', 'App\Http\Controllers\MainController@find')->name('find-form');

Route::middleware(['auth'])->group(function () {
    Route::resource('admin', 'App\Http\Controllers\AdminController', ['parameters' => [
        'admin' => 'id'
    ]]);
});

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Auth::routes([
    'reset' => false,
    'confirm' => false,
    'verify' => false,
    'register' => false,
]);

app/Models/Attraction.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

class Attraction extends Model
{
    use HasFactory;

    protected $table = "attraction";
    public $timestamps = false;

    public function index()
    {
        return DB::table('attraction', 'a')
            ->join('attraction_list as al', 'al.attraction_id', '=', 'a.attraction_type')
            ->select('a.*', 'al.attraction_name as attraction', 'al.attraction_price as price')
            ->get();
    }

    public function show($id)
    {
        return DB::table('attraction', 'a')
            ->join('attraction_list as al', 'al.attraction_id', '=', 'a.attraction_type')
            ->select('a.*', 'al.attraction_name as attraction', 'al.attraction_price as price')
            ->where('a.attraction_type', $id)->get();
    }

    public function IDshow($id)
    {
        return DB::table('attraction', 'a')
            ->join('attraction_list as al', 'al.attraction_id', '=', 'a.attraction_type')
            ->select('a.*', 'al.attraction_name as attraction', 'al.attraction_price as price')
            ->where('a.id', $id)->get();
    }
}

app/Models/Attraction_list.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

class Attraction_list extends Model
{
    use HasFactory;

    protected $table = "attraction_list";
    public $timestamps = false;

    public function allData()
    {
        return DB::table('attraction_list')->get();

    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/AdminController.php
<?php

namespace App\Http\Controllers;

use App\Models\Attraction;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class AdminController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.index', ['data' => (new \App\Models\Attraction)->index()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.add', ['attractions' => (new \App\Models\Attraction_list())->allData()]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $add = new Attraction;
        $add->guest_name = $request->input('guest_name');
        $add->attraction_type = $request->input('attraction_type');
        $add->data = $request->input('date');
        $add->save();
        return redirect()->route('admin.index');
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('admin.edit', [
            'result' => (new \App\Models\Attraction)->IDshow($id),
            'attractions' => (new \App\Models\Attraction_list())->allData()
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        DB::table('attraction')
            ->where('attraction.id', $id)
            ->update([
                'guest_name' => $request->input('guest_name'),
                'attraction_type' => $request->input('attraction_type'),
                'data' => $request->input('date')]);
        return redirect()->route('admin.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        DB::table('attraction')->where('id', '=', $id)->delete();
        return redirect()->route('admin.index');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/MainController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class MainController extends Controller
{
    protected function show()
    {
        return view('guest.index', ['data' => (new \App\Models\Attraction)->index()]);
    }


    public function find(Request $req)
    {
        $id = $req->input('attraction_id');
        return view('guest.find', ['data' => (new \App\Models\Attraction)->show($id)]);
    }
}

resources/views/admin/add.blade.php
@extends('admin.schema.schema')

@section('title-block','Admin')

@section('content')
    <div>
        <h1>Введіть інформацію про відвідувача</h1>
        <form action="{{route('admin.store')}}" method="post">
            @csrf
            <p>
                <label for="name">Ім'я відвідувача</label>
                <input type="text" placeholder="Ім'я відвідувача" id="name" name="guest_name" required>
            </p>
            <p>
                <label for="attraction_type">Атракціон</label>
                <select id="attraction_type" name="attraction_type" required>
                    @foreach($attractions as $attraction)
                        <option value='{{ $attraction->attraction_id }}'>{{ $attraction->attraction_name }}</option>
                    @endforeach
                </select>
            </p>
            <p>
                <label for="date">Дата</label>
                <input type="date" placeholder="Дата" id="date" name="date" required>
            </p>
            <p>
                <button type="submit">Додати</button>
                <a href="{{route('admin.index')}}">На головну</a>

            </p>
        </form>
    </div>
@endsection

resources/views/admin/edit.blade.php
@extends('admin.schema.schema')
@foreach($result as $res)
    @section('title-block','Edit '.$res->guest_name)

@section('content')
    <div>
        <h1>Введіть інформацію про відвідувача</h1>
        <form action="{{route('admin.update', ['id' => $res->id] )}}" method="post">
            <input name="_method" type="hidden" value="PUT">
            @csrf
            <p>
                <label for="name">Ім'я відвідувача</label>
                <input type="text" placeholder="Ім'я відвідувача" id="name" name="guest_name"
                       value="{{$res->guest_name}}" required>
            </p>
            <p>
                <label for="attraction_type">Атракціон</label>
                <select id="attraction_type" name="attraction_type" required>
                    @foreach($attractions as $attraction)
                        <option value='{{ $attraction->attraction_id }}'>{{ $attraction->attraction_name }}</option>
                    @endforeach
                </select>
            </p>
            <p>
                <label for="date">Дата</label>
                <input type="date" placeholder="Дата" id="date" name="date" value="{{$res->data}}" required>
            </p>
            <p>
                <button type="submit">Редагувати</button>
                <a href="{{route('admin.index')}}">На головну</a>

            </p>
        </form>
    </div>
@endsection
@endforeach

resources/views/admin/index.blade.php
@extends('admin.schema.schema')

@section('title-block','Admin')

@section('content')
    <p>
        <a href="{{route('admin.index')}}">Головна</a>
        |
        <a href="{{route('admin.create')}}">Додати</a>
        |
        <a href="{{ route('logout') }}"
           onclick="event.preventDefault();
        document.getElementById('logout-form').submit();">
            {{ __('Logout') }}
        </a>
    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
        @csrf
    </form>
    </p>
@endsection

resources/views/admin/schema/schema.blade.php
<!doctype html>
<html lang="ua">
<head>
    <title>@yield('title-block')</title>
    <meta charset="utf-8"/>
    <link rel="stylesheet" type="text/css" href="{{URL::asset('css/app.css')}}"/>
</head>
<body>
<p>
<h2>Парк розваг::Admin</h2>
@yield('content')
@if(isset($data))
    <table>
        <thead>
        <tr>
            <th>Ім'я відвідувача</th>
            <th>Атракціон</th>
            <th>Ціна</th>
            <th>Дата</th>
            <th>Дії</th>
        </tr>
        </thead>
        <tbody>
        @foreach ($data as $row)
            <tr>
                <td>{{$row->guest_name}}</td>
                <td>{{ $row->attraction}}</td>
                <td> {{$row->price}} </td>
                <td> {{$row->data}} </td>
                <td>
                    <a href="{{route('admin.edit',['id' => $row->id]) }}">Редагувати</a>
                    <form action="{{ route('admin.destroy' , $row->id)}}" method="POST">
                        <input name="_method" type="hidden" value="DELETE">
                        {{ csrf_field() }}
                        <button type="submit">Видалити</button>
                    </form>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
@endif
</body>
</html>

resources/views/guest/find.blade.php
@extends('guest.schema.schema')

@section('title-block','Find')
<?php
$model_attraction = new App\Models\Attraction_list();
$att_list = $model_attraction->allData();
?>
@section('content')
    <form action="{{route('find-form')}}" method="post">
        @csrf
        <p>
        <label for="id">Виберіть атракціон:</label>
        <select name="attraction_id" id="id">
        @foreach($att_list as $attraction)
            <option value="{{ $attraction->attraction_id }}"
                    @if (isset($_POST['attraction_id']) && $_POST['attraction_id'] == $attraction->attraction_name)
                    selected
                @endif
            >
                {{ $attraction->attraction_name }}
            </option>
        @endforeach
        </select>
            <button type="submit">Пошук</button>
        </p>
    </form>
    <p>
        <a href="{{route("index")}}">Назад</a>
    </p>
@endsection

resources/views/guest/index.blade.php
@extends('guest.schema.schema')

@section('title-block','Main')

@section('content')
    <p>
        <a href="{{route('find')}}">Пошук</a>
        |
        <a href="{{ route('login') }}">{{ __('Login') }}</a>
    </p>
@endsection

resources/views/guest/schema/schema.blade.php
<!doctype html>
<html lang="ua">
<head>
    <title>@yield('title-block')</title>
    <meta charset="utf-8"/>
    <link rel="stylesheet" href="../../../css/app.css">
</head>
<body>
<center>
<p>
<h2>Парк розваг</h2>
@yield('content')
@if(isset($data))
    <table>
        <thead>
        <tr>
            <th>Ім'я відвідувача</th>
            <th>Атракціон</th>
            <th>Ціна</th>
            <th>Дата</th>
        </tr>
        </thead>
        <tbody>
        @foreach ($data as $row)
            <tr>
                <td>{{$row->guest_name}}</td>
                <td>{{ $row->attraction}}</td>
                <td> {{$row->price}} </td>
                <td> {{$row->data}} </td>
            </tr>
        @endforeach
        </tbody>
    </table>
@endif
</center>
</body>
</html>

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    Парк розваг
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif

                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>